src/Entity/Notes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotesRepository")
 */
class Notes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_add;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_update;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="notes")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Recettes", inversedBy="notes")
     */
    private $recettes;

    public function __construct()
    {

        $this->date_add = new \DateTime();
        $this->date_update = new \DateTime();
        $this->activate = 1;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(?\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }

    public function getUsers(): ?users
    {
        return $this->users;
    }

    public function setUsers(?users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getRecettes(): ?recettes
    {
        return $this->recettes;
    }

    public function setRecettes(?recettes $recettes): self
    {
        $this->recettes = $recettes;

        return $this;
    }
}

src/Form/NotesType.php
<?php

namespace App\Form;

use App\Entity\Notes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NotesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('note')
            ->add('date_add')
            ->add('date_update')
            ->add('activate')
            ->add('users')
            ->add('recettes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Notes::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\SearchType;
use App\Form\UsersType;
use App\Repository\RecettesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/compte")
 */
class CompteController extends AbstractController
{
    /**
     * @Route("/", name="compte")
     */
    public function index()
    {
        return $this->render('compte/compte.html.twig', [
            'controller_name' => 'CompteController',
        ]);
    }

    /**
     * @Route("/users/show{id}", name="users_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('compte/users/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/users/{id}/edit", name="users_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->remove('password');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->setDateUpdate(new \DateTime());
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('users_show', ['id' => $user->getid()]);
        }

        return $this->render('compte/users/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/recherche", name="search")
     */
    public function recherche(Request $request, RecettesRepository $repo)
    {

        $searchForm = $this->createForm(SearchType::class);
        $searchForm->handleRequest($request);

        $recettes = $repo->findAll();

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {

            $title = $searchForm->getData()->getTitre();

            $recettes = $repo->search($title);


            if ($recettes == null) {
                $this->addFlash('erreur', 'Aucun article contenant ce mot clé dans le titre n\'a été trouvé, essayez en un autre.');

            }

        }

    }
}

src/Controller/NotesController.php
<?php

namespace App\Controller;

use App\Entity\Notes;
use App\Form\NotesType;
use App\Repository\NotesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/notes")
 */
class NotesController extends AbstractController
{
    /**
     * @Route("/", name="notes_index", methods={"GET"})
     */
    public function index(NotesRepository $notesRepository): Response
    {
        return $this->render('notes/index.html.twig', [
            'notes' => $notesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="notes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $note = new Notes();
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($note);
            $entityManager->flush();

            return $this->redirectToRoute('notes_index');
        }

        return $this->render('notes/new.html.twig', [
            'note' => $note,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="notes_show", methods={"GET"})
     */
    public function show(Notes $note): Response
    {
        return $this->render('notes/show.html.twig', [
            'note' => $note,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="notes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Notes $note): Response
    {
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('notes_index');
        }

        return $this->render('notes/edit.html.twig', [
            'note' => $note,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="notes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Notes $note): Response
    {
        if ($this->isCsrfTokenValid('delete'.$note->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($note);
            $entityManager->flush();
        }

        return $this->redirectToRoute('notes_index');
    }
}

templates/compte/notes/_delete_form.html.twig
<form method="post" action="{{ path('notes_delete', {'id': note.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ note.id) }}">
    <button class="btn">Delete</button>
</form>

templates/compte/notes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/compte/notes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Notes{% endblock %}

{% block body %}
    <h1>Edit Notes</h1>

    {{ include('notes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('notes_index') }}">back to list</a>

    {{ include('notes/_delete_form.html.twig') }}
{% endblock %}

templates/compte/notes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notes index{% endblock %}

{% block body %}
    <h1>Notes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Note</th>
                <th>Date_add</th>
                <th>Date_update</th>
                <th>Activate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for note in notes %}
            <tr>
                <td>{{ note.id }}</td>
                <td>{{ note.note }}</td>
                <td>{{ note.dateAdd ? note.dateAdd|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ note.dateUpdate ? note.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ note.activate ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('notes_show', {'id': note.id}) }}">show</a>
                    <a href="{{ path('notes_edit', {'id': note.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('notes_new') }}">Create new</a>
{% endblock %}

templates/compte/notes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Notes{% endblock %}

{% block body %}
    <h1>Create new Notes</h1>

    {{ include('notes/_form.html.twig') }}

    <a href="{{ path('notes_index') }}">back to list</a>
{% endblock %}

templates/compte/notes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notes{% endblock %}

{% block body %}
    <h1>Notes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ note.id }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ note.note }}</td>
            </tr>
            <tr>
                <th>Date_add</th>
                <td>{{ note.dateAdd ? note.dateAdd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_update</th>
                <td>{{ note.dateUpdate ? note.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Activate</th>
                <td>{{ note.activate ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('notes_index') }}">back to list</a>

    <a href="{{ path('notes_edit', {'id': note.id}) }}">edit</a>

    {{ include('notes/_delete_form.html.twig') }}
{% endblock %}