src/Entity/Recettes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecettesRepository")
 */
class Recettes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $top_recette;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $note_moyenne;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_add;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_update;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_delete;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="recettes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Preparations", mappedBy="recettes", cascade={"persist", "remove"})
     */
    private $preparations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="recettes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingredients", mappedBy="recettes")
     */
    private $ingredients;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaires", mappedBy="recettes", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favoris", mappedBy="recettes")
     */
    private $favoris;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notes", mappedBy="recettes")
     */
    private $notes;

    /**
     * @ORM\Column(type="text")
     */
    private $descriptions;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tmp_prepa;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tmp_cuisson;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->preparations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->date_add = new \DateTime();
        $this->date_update = new \DateTime();
        $this->activate = 0;
        $this->top_recette = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTopRecette(): ?bool
    {
        return $this->top_recette;
    }

    public function setTopRecette(bool $top_recette): self
    {
        $this->top_recette = $top_recette;

        return $this;
    }

    public function getNoteMoyenne(): ?float
    {
        return $this->note_moyenne;
    }

    public function setNoteMoyenne(float $note_moyenne): self
    {
        $this->note_moyenne = $note_moyenne;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getDateDelete(): ?\DateTimeInterface
    {
        return $this->date_delete;
    }

    public function setDateDelete(\DateTimeInterface $date_delete): self
    {
        $this->date_delete = $date_delete;

        return $this;
    }

    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }

    public function getCategories(): ?categories
    {
        return $this->categories;
    }

    public function setCategories(?categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection|Preparations[]
     */
    public function getPreparations(): Collection
    {
        return $this->preparations;
    }

    public function setPreparations(Preparations $preparations): self
    {
        $this->preparations = $preparations;

        // set the owning side of the relation if necessary
        if ($preparations->getRecettes() !== $this) {
            $preparations->setRecettes($this);
        }

        return $this;
    }

    public function getUsers(): ?users
    {
        return $this->users;
    }

    public function setUsers(?users $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|Ingredients[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredients $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->setRecettes($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredients $ingredient): self
    {
        if ($this->ingredients->contains($ingredient)) {
            $this->ingredients->removeElement($ingredient);
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecettes() === $this) {
                $ingredient->setRecettes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setRecettes($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecettes() === $this) {
                $commentaire->setRecettes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Favoris[]
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Favoris $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
            $favori->setRecettes($this);
        }

        return $this;
    }

    public function removeFavori(Favoris $favori): self
    {
        if ($this->favoris->contains($favori)) {
            $this->favoris->removeElement($favori);
            // set the owning side to null (unless already changed)
            if ($favori->getRecettes() === $this) {
                $favori->setRecettes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notes[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Notes $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setRecettes($this);
        }

        return $this;
    }

    public function removeNote(Notes $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getRecettes() === $this) {
                $note->setRecettes(null);
            }
        }

        return $this;
    }

    public function getDescriptions(): ?string
    {
        return $this->descriptions;
    }

    public function setDescriptions(string $descriptions): self
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    public function getTmpPrepa(): ?string
    {
        return $this->tmp_prepa;
    }

    public function setTmpPrepa(string $tmp_prepa): self
    {
        $this->tmp_prepa = $tmp_prepa;

        return $this;
    }

    public function getTmpCuisson(): ?string
    {
        return $this->tmp_cuisson;
    }

    public function setTmpCuisson(?string $tmp_cuisson): self
    {
        $this->tmp_cuisson = $tmp_cuisson;

        return $this;
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\SearchType;
use App\Form\UsersType;
use App\Repository\RecettesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/compte")
 */
class CompteController extends AbstractController
{
    /**
     * @Route("/", name="compte")
     */
    public function index()
    {
        return $this->render('compte/compte.html.twig', [
            'controller_name' => 'CompteController',
        ]);
    }

    /**
     * @Route("/users/show{id}", name="users_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('compte/users/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/users/{id}/edit", name="users_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->remove('password');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->setDateUpdate(new \DateTime());
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('users_show', ['id' => $user->getid()]);
        }

        return $this->render('compte/users/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/recherche", name="search")
     */
    public function recherche(Request $request, RecettesRepository $repo)
    {

        $searchForm = $this->createForm(SearchType::class);
        $searchForm->handleRequest($request);

        $recettes = $repo->findAll();

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {

            $title = $searchForm->getData()->getTitre();

            $recettes = $repo->search($title);


            if ($recettes == null) {
                $this->addFlash('erreur', 'Aucun article contenant ce mot clé dans le titre n\'a été trouvé, essayez en un autre.');

            }

        }

    }
}

src/Controller/RecettesController.php
<?php

namespace App\Controller;

use App\Entity\Ingredients;
use App\Entity\Preparations;
use App\Entity\Recettes;
use App\Form\RecettesType;
use App\Repository\PreparationsRepository;
use App\Repository\RecettesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/recettes")
 */
class RecettesController extends AbstractController
{
    /**
     * @Route("/liste", name="recettes_index", methods={"GET"})
     */
    public function index(RecettesRepository $recettesRepository): Response
    {
        return $this->render('admin/recettes/index.html.twig', [
            'recettes' => $recettesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/compte/recette/new", name="recettes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recette = new Recettes();
        $form = $this->createForm(RecettesType::class, $recette);
        $form->remove('top_recette');
        $form->remove('save');
        $form->remove('ingredients');
        $form->remove('preparations');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recette);
            $entityManager->flush();

            return $this->redirectToRoute('recettes_show');
        }

        return $this->render('compte/recettes/new.html.twig', [
            'recette' => $recette,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/compte/recettes/{id}", name="recettes_show", methods={"GET"})
     */
    public function show(Recettes $recette, PreparationsRepository $preparationsRepository): Response
    {
        $ingredients = $recette -> getIngredients();
        $preparations = $preparationsRepository -> getPreparationOrderByOrdre($recette -> getId());
        $category = $recette -> getCategories();

        return $this->render('compte/recettes/show.html.twig', [
            'recette' => $recette,
            'ingredients' => $ingredients,
            'preparations' => $preparations,
            'category' => $category
        ]);
    }

    /**
     * @Route("/recette/{id}/edit", name="admin_recettes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recettes $recettes, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(RecettesType::class, $recettes);
        $form->remove('users');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('image')->getData();
            if($file){
                $filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($filename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
            }
            $this->getDoctrine()->getManager()->flush();
            $entityManager = $this->getDoctrine()->getManager();
            $recettes->setImage($newFilename)
                ->setDateUpdate(new \DateTime());
            $entityManager->persist($recettes);
            $entityManager->flush();

            return $this->redirectToRoute('admin_recettes_show', ['id'=>$recettes->getid()]);
        }

        return $this->render('admin/recettes/edit.html.twig', [
            'recettes' => $recettes,
            'form' => $form->createView(),
        ]);
    }
}

templates/compte/recettes/new.html.twig
{% extends 'compte/compte.html.twig' %}

{% block title %}New Recettes{% endblock %}

{% block container %}
    <div class="col mx-auto p-0 m-0 divBody" id="contentFav">
        <h1 class="text-center m-5">PROPOSER UNE RECETTE</h1>
        <div>
            {{ form_start(form) }}
            <div class="border border-secondary col p-4 m-5 formRecette mx-auto">
                <div class="form-row">
                    <div class="form-group col">
                        <label for="categorie">Catégorie de recette:</label>

                        {{ form_widget(form.categories) }}
                    </div>
                    <div class="form-group col">
                        <label for="titre">Titre:</label>
                        {{ form_widget(form.titre) }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label for="tcuisson">Temps de cuisson:</label>
                        {{ form_widget(form.tmp_cuisson) }}
                    </div>

                    <div class="form-group col">
                        <label for="tprepa">Temps de préparation:</label>
                        {{ form_widget(form.tmp_prepa) }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="custom-file col mr-1 ml-1 mt-3 mb-3">
                        <label class="custom-file-label" for="imgRecette">Choisissez une photo</label>

                        {{ form_widget(form.image) }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label for="message">Description:</label>
                        {{ form_widget(form.descriptions, {'attr': {'rows': '6'}}) }}
                    </div>
                </div>
                <div class="text-right">
                    <button class="btn btn-outline-dark">{{ button_label|default('Proposer') }}</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/compte/recettes/show.html.twig
{% extends 'compte/compte.html.twig' %}

{% block title %}Recette en cours{% endblock %}

{% block container %}
    <div class="col mx-auto p-0 m-0 divBody" id="contentFav">
        <h1 class="text-center m-5">RECETTE EN COURS</h1>
        <div class="container mb-5">
            <h2 class="mb-5 text-center">{{recette.titre}}</h2>
            <div class="justify-content-around row">
                <div class="col-md-3 mr-5">
                    <figure>
                        <img class="border border-dark" width="280" src="{{asset('assets/img/' ~ recette.image)}}"
                             alt="image de la recette">
                    </figure>
                </div>
                <div class="col-md-7">
                    <div class="divNote">
                        <div class="descrip rating"><!--
                                --><a href="#5" title="Donner 5 étoiles">☆</a><!--
                                --><a href="#4" title="Donner 4 étoiles">☆</a><!--
                                --><a href="#3" title="Donner 3 étoiles">☆</a><!--
                                --><a href="#2" title="Donner 2 étoiles">☆</a><!--
                                --><a href="#1" title="Donner 1 étoile"><span>Note: </span>☆</a>
                        </div>
                    </div>
                    <br><br>
                    <span class="descrip">Description:</span>
                    <p class="text-justify">
                        {{ recette.descriptions }}
                    </p>
                </div>
            </div>
        </div>
        <div class="container mb-5">
            <div class="justify-content-around row">
                <div class="ingredients col-md-3 border border-dark pt-2 mb-3">
                    <span class="descrip">Ingrédients:</span><br><br>
                    <ul>
                    {% for ingredient in ingredients %}
                        <li>{{ ingredient.quantite }} {{ ingredient.nom }}</li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="preparation col-md-7 p-0">
                    <div class="border border-dark p-2 mb-3" height="80">
                        <h6 class="text-center pb-3">Temps total: 15 mins</h6>
                        <div class="row">
                            <h6 class="col-6 text-center">Préparation: {{recette.tmpPrepa}}</h6>
                            <h6 class="col-6 text-center">Cuisson: {{recette.tmpCuisson}}</h6>
                        </div>
                    </div>
                    <div class="prep border border-dark p-3">
                        <span class="descrip">Préparations:</span>
                        {% for preparation in preparations %}
                        <p class="pt-2 pb-2">
                            {{preparation.ordres}} - {{ preparation.etapes }}
                        </p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="text-right mr-5">
                <a href="{{ path('ingredients_show', {'id': recette.id}) }}" class="btn btn-dark btn" type="button">{{ button_label|default('Ingrédient +') }}</a>
                <a href="{{ path('preparations_show', {'id': recette.id}) }}" class="btn btn-dark btn" type="button">{{ button_label|default('Etape +') }}</a>
                <a href="{{ path('compte') }}" class="btn btn-dark" type="button">{{ button_label|default('Valider') }}</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}