src/Entity/Messages.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessagesRepository")
 */
class Messages
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $objet;

    /**
     * @ORM\Column(type="boolean")
     */
    private $lu;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_add;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_delete;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="messages")
     */
    private $users;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activate;

    public function __construct()
    {
        $this->date_add = new \DateTime();
        $this->lu = 0;
        $this->activate = 1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): self
    {
        $this->objet = $objet;

        return $this;
    }

    public function getLu(): ?bool
    {
        return $this->lu;
    }

    public function setLu(bool $lu): self
    {
        $this->lu = $lu;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getDateDelete(): ?\DateTimeInterface
    {
        return $this->date_delete;
    }

    public function setDateDelete(?\DateTimeInterface $date_delete): self
    {
        $this->date_delete = $date_delete;

        return $this;
    }

    public function getUsers(): ?users
    {
        return $this->users;
    }

    public function setUsers(?users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('objet')
            ->add('lu')
            ->add('message')
            ->add('date_add')
            ->add('date_delete')
            ->add('activate')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\SearchType;
use App\Form\UsersType;
use App\Repository\RecettesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/compte")
 */
class CompteController extends AbstractController
{
    /**
     * @Route("/", name="compte")
     */
    public function index()
    {
        return $this->render('compte/compte.html.twig', [
            'controller_name' => 'CompteController',
        ]);
    }

    /**
     * @Route("/users/show{id}", name="users_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('compte/users/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/users/{id}/edit", name="users_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->remove('password');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->setDateUpdate(new \DateTime());
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('users_show', ['id' => $user->getid()]);
        }

        return $this->render('compte/users/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/recherche", name="search")
     */
    public function recherche(Request $request, RecettesRepository $repo)
    {

        $searchForm = $this->createForm(SearchType::class);
        $searchForm->handleRequest($request);

        $recettes = $repo->findAll();

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {

            $title = $searchForm->getData()->getTitre();

            $recettes = $repo->search($title);


            if ($recettes == null) {
                $this->addFlash('erreur', 'Aucun article contenant ce mot clé dans le titre n\'a été trouvé, essayez en un autre.');

            }

        }

    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use App\Repository\MessagesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/messages")
 */
class MessagesController extends AbstractController
{
    /**
     * @Route("/", name="messages_index", methods={"GET"})
     */
    public function index(MessagesRepository $messagesRepository): Response
    {
        return $this->render('messages/index.html.twig', [
            'messages' => $messagesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="messages_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $message = new Messages();
        $form = $this->createForm(MessagesType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('messages_index');
        }

        return $this->render('messages/new.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="messages_show", methods={"GET"})
     */
    public function show(Messages $message): Response
    {
        return $this->render('messages/show.html.twig', [
            'message' => $message,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="messages_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Messages $message): Response
    {
        $form = $this->createForm(MessagesType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('messages_index');
        }

        return $this->render('messages/edit.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="messages_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Messages $message): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($message);
            $entityManager->flush();
        }

        return $this->redirectToRoute('messages_index');
    }
}

templates/compte/messages/_delete_form.html.twig
<form method="post" action="{{ path('messages_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/compte/messages/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/compte/messages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Messages{% endblock %}

{% block body %}
    <h1>Edit Messages</h1>

    {{ include('messages/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('messages_index') }}">back to list</a>

    {{ include('messages/_delete_form.html.twig') }}
{% endblock %}

templates/compte/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages index{% endblock %}

{% block body %}
    <h1>Messages index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Objet</th>
                <th>Lu</th>
                <th>Message</th>
                <th>Date_add</th>
                <th>Date_delete</th>
                <th>Activate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.email }}</td>
                <td>{{ message.objet }}</td>
                <td>{{ message.lu ? 'Yes' : 'No' }}</td>
                <td>{{ message.message }}</td>
                <td>{{ message.dateAdd ? message.dateAdd|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ message.dateDelete ? message.dateDelete|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ message.activate ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('messages_show', {'id': message.id}) }}">show</a>
                    <a href="{{ path('messages_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('messages_new') }}">Create new</a>
{% endblock %}

templates/compte/messages/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Messages{% endblock %}

{% block body %}
    <h1>Create new Messages</h1>

    {{ include('messages/_form.html.twig') }}

    <a href="{{ path('messages_index') }}">back to list</a>
{% endblock %}

templates/compte/messages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages{% endblock %}

{% block body %}
    <h1>Messages</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ message.email }}</td>
            </tr>
            <tr>
                <th>Objet</th>
                <td>{{ message.objet }}</td>
            </tr>
            <tr>
                <th>Lu</th>
                <td>{{ message.lu ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ message.message }}</td>
            </tr>
            <tr>
                <th>Date_add</th>
                <td>{{ message.dateAdd ? message.dateAdd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_delete</th>
                <td>{{ message.dateDelete ? message.dateDelete|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Activate</th>
                <td>{{ message.activate ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('messages_index') }}">back to list</a>

    <a href="{{ path('messages_edit', {'id': message.id}) }}">edit</a>

    {{ include('messages/_delete_form.html.twig') }}
{% endblock %}